### ISSUE TITLE
Chrome extension loses text when it loses focus

### ISSUE THREAD

**Issue by anisaraf** [karlicoss/grasp#10]
The extension is great! It would be great if it retained the text if it loses focus and clears the text on capture. 

I use it to take notes, and frequently it loses focus losing all the text. 

Thanks!

**Comment by karlicoss** [comment]
Hey @anisaraf , glad that it's useful to you!
Yeah, this actually happened to me couple of times as well. I'll try to fix soonish.

**Comment by karlicoss** [comment]
Ok, should be fixed now (in version 0.6.4). Already available for firefox; chrome will take some time for approval. Feel free to close the issue if it's fixed for you!

**Comment by anisaraf** [comment]
Thanks for the quick fix. Works great now!
