### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by OrionRandD** [karlicoss/grasp#14]
It seems that there is no firefox addon anymore or link is wrong...

**Comment by karlicoss** [comment]
@OrionRandD whoops, sorry for that. [Here it is](https://addons.mozilla.org/en-US/firefox/addon/grasp) and I fixed the readme as well.

**Comment by OrionRandD** [comment]
Thx a lot. I've installed it and now everything is working fine... :)

**Comment by mathias** [comment]
README link appears broken again for Firefox.

**Comment by karlicoss** [comment]
@mathias ah, I updated only one of two links out of two last time, sorry!
Thanks for letting me know, fixed!

**Comment by nathanbraun** [comment]
Does this still work in firefox? Link doesn't appear to go anywhere.

**Comment by karlicoss** [comment]
Sigh! Apparently it was temporary hidden by Mozilla because of some boilerplate `evals` generated by Webpack.
I'll try to fix this asap.

**Comment by karlicoss** [comment]
@nathanbraun ok, I think it's fixed now! Hopefully it works for you.
