### ISSUE TITLE
missing systemd directories during setup

### ISSUE THREAD

**Issue by gambhiro** [karlicoss/grasp#19]
Hello! This is a gift. Thanks for the fantastic web clipping tool!

A small bug:

I didn't have user systemd folders, and the setup script errored out when trying to write `~/.config/systemd/user/grasp.service`.

I created the `~/.config/systemd/user/` and then it worked fine.

**Comment by karlicoss** [comment]
Thanks, good catch. Need to find some generic systemd installer; have ran into similar issue in couple of other projects too.
