### ISSUE TITLE
Feature idea: quote highlighted text

### ISSUE THREAD

**Issue by mathias** [karlicoss/grasp#21]
Just a quick idea that would automate what I’m already doing. I highlight some part of the page I want included in the capture, then copy and paste it into the note. The extension would just have to pull in any selected text to the note input when clicked. This could probably wrap the highlighted/selected text in #+BEGIN_QUOTE / #+END_QUOTE

**Comment by karlicoss** [comment]
Hey, I think it's capable of what you want to do!

You'd need to pass custom --template to the server and within the template use something like `#+begin_quote\n%:selection\n#+end_quote`.

The magig is happening [here](https://github.com/karlicoss/grasp/blob/3984bfb5db559f00e8518802539dc34760272d6f/server/org_tools.py#L21) and there are some tests in the file to use as a reference. Admit it's not very discoverable, will update readme :)

Let me know if that works for you!

**Comment by mathias** [comment]
Oh cool, I didn't realize you already captured :selection because it doesn't show it in the "Enter your comments" box in the extension. Thanks!
