### ISSUE TITLE
setup fails when systemd user directory does not exist

### ISSUE THREAD

**Issue by mathias** [karlicoss/grasp#25]
When the directory does not exist in user's home directory: 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/mathiasx/.config/systemd/user/grasp.service'
```

After creating `/home/<username>/.config/systemd/user/` it works. Should the `setup` script create those directories if they don't exist?

**Comment by karlicoss** [comment]
Thanks for reporting! Yes, it's a [known issue](https://github.com/karlicoss/grasp/issues/19), just didn't get to fix it yet :(

**Comment by karlicoss** [comment]
closing as duplicate!
