### ISSUE TITLE
Add Markdown support

### ISSUE THREAD

**Issue by t-e-r-m** [karlicoss/grasp#31]
Hi, would it be possible to convert the selected text to markdown and then capture it? I have (unsuccessfully) tried my hand at it. I tried using the file `copy.js` from https://github.com/0x6b/copy-selection-as-markdown instead of

`code: "window.getSelection().toString();"`

in `background.js`, but the selection variable is always empty.

(I am a js noob)

Markdown support would be really, really great.

**Comment by karlicoss** [comment]
Hey, actually I don't think you need any extension changes to support markdown!
Extension just sends stuff to the server bit, it doesn't handle formatting on its own.

It's a bit undocumented, but you should be able to specify a custom [`--template`](https://github.com/karlicoss/grasp#running), and simply use markdown syntax for it.

For example:

    server/grasp_server.py --path links.md --port 15555 --template $'## [%:description](%:link) %:tags\nSelection\n%:selection\n\nComment\n%:comment\n'

(Note the `$` before the string, it's necessary for `\n` to be properly handled. You don't need to pass it to `server/setup` though. I guess I need to document this).

This results in 
```
## [Add Markdown support · Issue #31 · karlicoss/grasp](https://github.com/karlicoss/grasp/issues/31) 
Selection:
Markdown support would be really, really great.

Comment:
sure!
```

Let me know if it works for you!
If there is something working not exactly as you expect, you can try hacking [as_org](https://github.com/karlicoss/grasp/blob/4bc8f011227d1baa18b4e98543561534065490d8/server/org_tools.py#L51) function.

If you think some other template makes more sense, let me know, I'll add it to the examples!

**Comment by t-e-r-m** [comment]
Thanks for the quick reply. I'm hoping there can be markdown for the selected text and not just the link. `turndown` (https://github.com/domchristie/turndown) is what I was really trying to integrate. 

There's a demo here: http://domchristie.github.io/turndown/

Having markdown support helps one copy the text as well as the url(s) it links to, which is super helpful as a store of adjacent links and knowledge. Plus, it clearly separates code and text, which is awesome because SRC blocks in org have good support for syntax highlighting markdown.

**Comment by karlicoss** [comment]
Ah, gotcha. Yeah, it makes sense, but I think it's out of scope of this extension, because the idea is keeping it small and reliable.

Actually there is an org-mode capture extension that works in the way you describe: https://github.com/alphapapa/org-protocol-capture-html (i.e. by converting HTML to org-mode, preserving the markup like links, bold text, etc)

There are some snippets of code there (in bookmarklets) that are extracting the HTML from selection. So perhaps you can modify them and combine with turndown?

**Comment by t-e-r-m** [comment]
Thanks for the suggestion, I'll look into it. Feel free to close the issue.

Grasp is an awesome program btw, I use it everyday!
