### ISSUE TITLE
Running server/setup fails on macOS

### ISSUE THREAD

**Issue by LOG67** [karlicoss/grasp#32]
Running Server/Setup fails on macOS with error "FileNotFoundError: [Errno 2] No such file or directory: 'systemctl': 'systemctl'".

This is understandable since macOS does not have systemctl, instead it has launchctl.

**Comment by karlicoss** [comment]
Yeah, and I don't have an OSX around to figure it out.
Perhaps you could help? I believe this should be the minimal script to run it
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>com.github.karlicoss.grasp</string>

                <key>ProgramArguments</key>
                <array>
                	<string>/PATH/TO/GRASP_REPOSITORY/grasp/server.py</string>
                	<string>--port=PORT</string>
                	<string>--path=PATH</string>
                	<string>--template=TEMPLATE</string>
                </array>

		<key>RunAtLoad</key>
		<true/>
                <key>KeepAlive</key>
                <true/>
	</dict>
</plist>
```

You should put it in `~/Library/LaunchAgents/com.github.karlicoss.grasp.plist`.
And I [believe](https://superuser.com/a/1334488/300795) then you can load it with `launchctl load -w ~/Library/LaunchAgents/com.github.karlicoss.grasp.plist`.

Let me know if it works/fails?

Feel free to remove the arguments you don't need to pass from the file, the only important thing is to specify the first one, which is full path to the server executable.

**Comment by LOG67** [comment]
Thanks! The plist worked.
One caveat of the plist is that it does not expand `~` for paths. 

If you want I can work on the Setup script so that on mac it installs the daemon by adding the required plist file and runs the `launchctl` command.

**Comment by karlicoss** [comment]
Thanks, would be great!

**Comment by behaghel** [comment]
@LOG67 by the look of [this](https://apple.stackexchange.com/a/364976) you may not be able to refer to `~` or `$HOME` but you can add a level of indirection by starting a shell that starts the server by referencing its path. I actually tried it and it does the trick.

**Comment by mediapathic** [comment]
Some additional notes for people who might run into the same problems I did:

When you want to reload the file after you've changed the template (or, uh, gotten the path wrong, ahem) the invocation is

```
❯ launchctl stop com.github.karlicoss.grasp                                                                                                                                                                                                
❯ launchctl unload ~/Library/LaunchAgents/com.github.karlicoss.grasp.plist                                                                                                                                                                 
❯ launchctl load -w ~/Library/LaunchAgents/com.github.karlicoss.grasp.plist        
```

Also of note: xml is weird with the templating. Don't quote it,`\n` does not work as you might expect, everything in that string is taken literally, so you have to actually put in newlines, and, yes, if you follow the indentation of your xml file as looks correct you will wind up with indentations in your output. And make sure to put a newline before the final `</string>` for the same reasons.

**Comment by albertz** [comment]
Hey, I already wrote [here](https://github.com/karlicoss/promnesia/issues/15#issuecomment-786587555):

I think such a thing (installing some user service) is generally useful. I also have some script ([this](https://github.com/albertz/mouse-scroll-wheel-acceleration-userspace)) where I would want to have such a systemd install script (or launchctl on MacOSX, and no idea what Windows has, or other Unixes).

Maybe it makes sense if we package sth like this as a separate PIP package, so that we can easily make use of it? (Or maybe there is already some project/package like this?)

I have such an install script for MacOSX [here](https://github.com/albertz/timecapture/blob/master/install-osx-launchd-agent.sh).
