### ISSUE TITLE
How to capture the website with my own comments?

### ISSUE THREAD

**Issue by fu123456** [karlicoss/grasp#33]
I use this package in my Firefox, but it can not capture my comments. My org template is as follows:
```
python /home/***/nstall/grasp/server/grasp_server.py --path /home/***/org/bookmark.org  --template  $'** [[%:link][%:description]] %:tags\n%U\n' &
```
How can I capture the website with my witten comments? Thx.

**Comment by karlicoss** [comment]
Hi, sorry for a late reply! 
I think you need to use `%:selection` or/and `%:comment`, you can find some examples here: https://github.com/karlicoss/grasp/blob/af24c991579986cec73695daa8318e7831049305/server/org_tools.py#L91-L109

**Comment by fu123456** [comment]
> Hi, sorry for a late reply!
> I think you need to use `%:selection` or/and `%:comment`, you can find some examples here:
> 
> https://github.com/karlicoss/grasp/blob/af24c991579986cec73695daa8318e7831049305/server/org_tools.py#L91-L109

Thanks. Now it does work well. Grasp is one of my most commonly used plugins.
