### ISSUE TITLE
Only capture selection and comments if present

### ISSUE THREAD

**Issue by aancel** [karlicoss/grasp#37]
Hello,

First of all, I would like to thank you for this great extension, and for promnesia too !

Regarding this issue, I'm wondering if there would be any way of inserting comments and selections, only if the user added a comment or made one or several selections. By default, the template would only contain a basic template (without comments or/selections entries) defined by the user, and if selection/comments are made they then would be included.
An idea on this side could be to add new options to the server to allow specifying the templates for comments and selections, and only proceed this way if those options are present. I do know that it break a bit the org-capture template definition and feel free to close this issue if you think that this is a behavior you wouldn't want to include.

What do you think about this ?

**Comment by karlicoss** [comment]
Hey, sorry for a late reply! And glad you're enjoying grasp and promnesia :) 
Hmm, for me the selection/comments only appear if there was something actually selected, as expected; here's the bit of code which is responsible for it https://github.com/karlicoss/grasp/blob/4bc8f011227d1baa18b4e98543561534065490d8/server/org_tools.py#L81-L84
Is it not the case for you?
