### ISSUE TITLE
Newlines being written as '\n'

### ISSUE THREAD

**Issue by AB1908** [karlicoss/grasp#39]
Hi again. I stumbled across your extension and it pairs very nicely with my newfound interest in org-mode. I wanted to use a custom template so I can get captures similar to Orgzly's format. I passed in the custom template as a command line argument, `* %:description \n:PROPERTIES:\n:CREATED:  %U\n:END:\n %:link\n %:tags\n %:initial\n` but in the file, it shows up as a single line instead of with line breaks.

- Experimented with `\r\n` as I'm on Windows
- Works fine when running through a debugger in VSCode
- Writes work when I take the formatted template from the debugger and write to the capture file through Python REPL
- Issue occurs across all three terminals (Command Prompt, powershell, Windows Terminal)

Environment details: 
```
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
```

I'll try reproducing this in a clean environment but for now my workaround is to directly modify the default template in `org_tools.py`. Any tips for debugging and creating a fix would be great.

**Comment by karlicoss** [comment]
Hey, sorry hmm not sure about Windows to, haven't had much experience with it. 
You might want to experiment with single/double quotes around the template maybe... or search abound newline escaping in CMD scripts

**Comment by AB1908** [comment]
Yeah, Windows sucks for sure haha. Do you think it makes sense to include a predefined template choice and keep an argument to select it?

**Comment by AB1908** [comment]
I got around this by changing the template in `server/org_tools.py`.
