### ISSUE TITLE
Document API for grasp/server

### ISSUE THREAD

**Issue by snoblenet** [karlicoss/grasp#41]
Thanks for Grasp.

It is possible for you to briefly document the API for grasp/server?

I can picture myself hitting it with a range of personal tools other than the browser extension.

**Comment by karlicoss** [comment]
Hi! 
You can basically see what the 'API' is here: https://github.com/karlicoss/grasp/blob/master/server/test_grasp.py#L27-L41

So essentially just a bunch of fields passed in a post request. IMO there is no good reason to use Grasp outside the browser, it's just easier to construct a bit of org-mode and append it to a file. This is basically all that Grasp server does:  https://github.com/karlicoss/grasp/blob/master/server/grasp_server.py#L80-L92

The bit that possibly could be reused in other tools is the code that can generate org-mode here https://github.com/karlicoss/grasp/blob/master/server/org_tools.py . There is also some relevant discussion in orgparse https://github.com/karlicoss/orgparse/issues/11

**Comment by snoblenet** [comment]
Thanks.
